name: Daily Diff Check

on:
  schedule:
    # Every day at 11:00 UTC
    - cron: "0 11 * * *"
  workflow_dispatch: # manual trigger

jobs:
  diff-report:
    runs-on: ubuntu-latest

    env:

      GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper and send diff email
        run: python -m scraper.main
